language: scala

scala:
  - 2.11.2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml mono-devel 
 - travis_retry git clone --recursive --depth 1 --branch last-compilable-version https://github.com/qifun/haxe.git
 - (cd haxe && make && sudo make install)
 - travis_retry sudo haxelib setup .haxelib
 - travis_retry sudo haxelib install nodejs
 - travis_retry sudo haxelib install hxjava
 - travis_retry sudo haxelib install hxcs
 - travis_retry sudo haxelib install continuation=1.2.0
 - travis_retry sudo haxelib git hxparse https://github.com/Simn/hxparse.git development src
 - travis_retry sudo haxelib git haxeparser https://github.com/qifun/haxeparser qifun.git src
 - travis_retry sudo haxelib git HUGS https://github.com/qifun/HUGS.git
