language: scala

scala:
  - 2.11.2
  - 2.10.4

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

env:
  matrix:
    # The lastest Haxe
    - SBT_TEST_CONFIGURATION=test HAXE_FILE=haxe_latest.tar.gz
    # Haxe 3.2.0
    - SBT_TEST_CONFIGURATION=test HAXE_FILE=haxe_2015-05-12_master_77d171b.tar.gz
    # Disable test cases for old Haxe version
    # - SBT_TEST_CONFIGURATION=test HAXE_FILE=haxe_2014-09-19_development_9f5b3f5.tar.gz
    - SBT_TEST_CONFIGURATION=test HAXE_FILE=haxe_2014-10-21_development_a05b532.tar.gz
    # Disable currently, because of https://github.com/qifun/sbt-haxe/issues/8
    # - SBT_TEST_CONFIGURATION=csharp-test HAXE_FILE=haxe_latest.tar.gz

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml
 - travis_retry wget http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/"$HAXE_FILE"
 - sudo tar zxvf "$HAXE_FILE"
 - sudo mv haxe-*/ haxe/
 - export PATH=$PATH:`pwd`/haxe
 - export HAXE_STD_PATH=`pwd`/haxe/std
 - travis_retry haxelib setup .haxelib
 - if [[ "$SBT_TEST_CONFIGURATION" = "test" ]]; then travis_retry haxelib install hxjava; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry sudo apt-get install mono-devel; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry haxelib install hxcs; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry haxelib git HUGS https://github.com/qifun/HUGS.git; fi
 - travis_retry haxelib install continuation
 - travis_retry haxelib git hxparse https://github.com/Simn/hxparse.git development src
 - travis_retry haxelib git haxeparser https://github.com/qifun/haxeparser.git qifun src

script: sbt ++$TRAVIS_SCALA_VERSION $SBT_TEST_CONFIGURATION:test
