language: scala

scala:
  - 2.11.2
  - 2.10.4

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  - SBT_TEST_CONFIGURATION=test
  # Disable currently, because of https://github.com/qifun/sbt-haxe/issues/8
  # - SBT_TEST_CONFIGURATION=csharp-test

before_install:
 - travis_retry sudo add-apt-repository ppa:eyecreate/haxe -y
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -qq neko ocaml
 - travis_retry git clone --recursive --depth 1 --branch development https://github.com/HaxeFoundation/haxe.git
 - (cd haxe && make && sudo make install)
 - travis_retry sudo haxelib setup .haxelib
 - if [[ "$SBT_TEST_CONFIGURATION" = "test" ]]; then travis_retry sudo haxelib install hxjava; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry sudo apt-get install mono-devel; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry sudo haxelib install hxcs; fi
 - if [[ "$SBT_TEST_CONFIGURATION" = "csharp-test" ]]; then travis_retry sudo haxelib git HUGS https://github.com/qifun/HUGS.git; fi
 - travis_retry sudo haxelib install continuation
 - travis_retry sudo haxelib git hxparse https://github.com/Simn/hxparse.git development src
 - travis_retry sudo haxelib git haxeparser https://github.com/qifun/haxeparser qifun.git src

script: sbt ++$TRAVIS_SCALA_VERSION $SBT_TEST_CONFIGURATION:test
